### ISSUE TITLE
MicroCMSGetListQueriesでfieldsを指定する際に参照コンテンツの指定ができない

### ISSUE THREAD

**Issue by alpaca1231** [tsuki-lab/microcms-ts-sdk#125]
## 概要

microCMSのドキュメントによると、リスト形式のAPIにて`fields`で取得する要素を指定する際に
![image](https://github.com/tsuki-lab/microcms-ts-sdk/assets/80532711/779f04ca-0886-40a2-a151-cd645f678137)
> author.organization.nameのようにドットでつないでキーを指定することで参照コンテンツの要素も指定できます。
引用：https://document.microcms.io/content-api/get-list-contents#h7462d83de4

と記載があります。

しかし、[MicroCMSGetListDetailQueries](https://github.com/tsuki-lab/microcms-ts-sdk/blob/5f2b44b33db1a2e33b257b152612fe8f928622b1/src/types.ts#L79)や[MicroCMSGetListQueries](https://github.com/tsuki-lab/microcms-ts-sdk/blob/5f2b44b33db1a2e33b257b152612fe8f928622b1/src/types.ts#L101)や型はネストされた参照コンテンツに対応しておらず、参照コンテンツのキーを指定することができません。

```ts
type Content = {
  text: string;
  hoge: {
    id: string;
    name: string;
  };
};

client
  .getList({
    endpoint: 'contents',
    queries: {
      fields: ['id', 'text', 'publishedAt', 'hoge.name']
      // Error: 型 '"hoge.name"' を型 '"id" | keyof MicroCMSDate | keyof Content' に割り当てることはできません。
    }
  })
  .then((res) => res.contents[0]);
```

## 期待する結果

`fields`に参照コンテンツのキーを指定できるようにする

## 備考

おそらくネストされた参照コンテンツまで型定義に含めることは難しいと思いますので`string[]`を許容していただく対応が必要と思います。

**Comment by tsuki-lab** [comment]
@alpaca1231 
現在このSDKで提供しているfieldsでは確かにそのような型エラーが発生してしまいますね。
任意のコンテンツキーを指定した際のレスポンスの型定義を`unknown`として返すことができるか検討してみます。

より良いアイデアがあれば、コントリビュートもお待ちしてます。ありがとうございます。
